name: test
channels:
  - conda-forge
dependencies:
    # Core
  - python
  - pyyaml
  - py-cpuinfo
  - psutil
  - qcelemental >=0.9.0
  - pydantic >=0.30.1

    # Testing
  - pytest
  - pytest-cov
  - codecov
