language: python

# Run jobs on container-based infrastructure, can be overridden per job
dist: trusty

matrix:
  include:
    - os: linux
      python: 2.7
      env: 
        - PYTHON_VER=2.7
        - PROG=RDKIT
    - os: linux
      python: 3.5
      env:
        - PYTHON_VER=3.5
        - PROG=RDKIT
  allow_failures:
    - os: linux
      python: 3.6
      env:
        - PYTHON_VER=3.5
        - PROG=PSI4

before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Install the Python environemt
  - source devtools/travis-ci/before_install.sh
  - python -V

install:

    # Create test environment for package
  - |
    if [ $PROG == "RDKIT" ]; then
      conda create -n test python=$PYTHON_VER pytest pyyaml pytest-cov py-cpuinfo rdkit -c rdkit
    else
      conda create -n test python=$PYTHON_VER pytest pyyaml pytest-cov py-cpuinfo psi4 -c psi4
    fi
  - source activate test

    # Install pip only modules
  - pip install codecov

    # Build and install package
  - python setup.py develop


script:
  - pytest -v --cov=qcengine/ qcengine/tests/

notifications:
    email: false

after_success:
  - codecov
