# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6

before_install:
    # Additional info about the build
  - uname -a
  - free -m
  - df -h
  - ulimit -a

    # Setup python environment
  - pip install --upgrade pip setuptools
  - python -V

install:
    # Install depends
  - pip install py-cpuinfo

    # Install module and coverage
  - pip install codecov pytest pytest-cov
  - pip install -e .

script:
  - py.test -v --cov=qcengine

notifications:
    email: false

after_success:
  - codecov
