package:
  name: QCEngine
  version: "0.0.0"

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - py-cpuinfo
    - pyyaml

test:
  requires:
    - pytest
  imports:
    - qcengine

about:
  home: https://github.com/MolSSI/QCEngine
  license: BSD-3-Clause License
