package:
  name: qcengine
  version: "0.1.0"

source:
  path: ../..

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - py-cpuinfo
    - pyyaml

test:
  requires:
    - pytest
  imports:
    - qcengine

about:
  home: https://github.com/MolSSI/QCEngine
  license: BSD-3-Clause License
