name: qcengine-docs
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3
    - sphinx
    - sphinx_rtd_theme
    - sphinx-automodapi
    - graphviz
    
      # QCEngine depends
    - numpy
    - pydantic >=0.18.0
    - qcelemental >=0.2.1
