name: qcengine-docs
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3
    - sphinx
    - sphinx_rtd_theme
    - sphinx-automodapi
    - graphviz
    
      # QCEngine depends
    - numpy
    - pydantic >=0.20.0
    - qcelemental >=0.4.0

    - pip:
      - git+git://github.com/MolSSI/qcarchive-sphinx-theme#egg=qcarchive_sphinx_theme
